### PR TITLE
feat: contributors list

### PR DESCRIPTION
**Pull request by vinckr**
A quick and dirty python script that spits out a list of all contributors.
I am sure there is lots of room for improvement.

### CODE REVIEW

**Comment by aeneasr** [comment]
Could you print out the list of contributors with the days contributions were made? So we get an activity graph of community contributions over time!

Also I'd recommend using GitHub's JavaScript/Node API instead because you could then make this to a GitHub Action which runs automatically every night: https://octokit.github.io/rest.js/v18/

**Comment by vinckr** [comment]
Sounds like a good idea!
I think I would put the activity graph in a different output then, since I need just the list of names for the mailout checklists. 
But the idea was to have a versatile little code that can output also the activity, stars and basically all interesting information. 
I will look how to port it to node.js today.

**Comment by aeneasr** [comment]
You can probably also just use GraphQL or maybe even the standard GitHub Search (in the UI) :)

**Comment by vinckr** [comment]
I am currently trying to get this to work: https://github.com/octokit/request.js/
I guess I could use https://api.github.com/repos/ory/kratos/contributors?anon=1 directly, but it does not display all contributors for some reason, only the first 30.

**Pull request closed without merging**
